version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: social-graph-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_graph
    ports:
      - "5436:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
# -------------------------------------------------------
# Connection URL:
# postgresql://admin:password@localhost:5436/social_graph

